[tool.poetry]
name = "runtime-syspath"
version = "0.1.16"
authors = ["Greg Kedge <gregwork@kedges.com>"]
description = "Functions show and find each 'src' directory under working directory and add each to sys.path."
readme = "README.md"
homepage = "https://github.com/gkedge/runtime-syspath"
repository = "https://github.com/gkedge/runtime-syspath"
license = "MIT"
keywords = ["testing", "sys.path", "packaging", "dependency", "infer", "pyproject.toml"]
include = ["docs/**/*"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Developers",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/gkedge/runtime-syspath/issues"

[tool.poetry.dependencies]
python = "~3.6"

[tool.poetry.dev-dependencies]
pytest = "~5.4.1"
wheel = "tox-wheel"
isort = "~5.4.2"
black = "~20.8b1"
pylint = "~2.6.0"

[tool.isort]
profile = "black"
line_length = 100
#honor-noqa = "true"
#remove-redundant-aliases = "true"
combine_as_imports = "True"

[black]
line-length = 100
target-version = ["py37|py38"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
