[tool.poetry]
name = "runtime-syspath"
version = "0.1.12"
authors = ["Greg Kedge <gregwork@kedges.com>"]
description = "Functions show and find each 'src' directory under working directory and add each to sys.path."
readme = "README.md"
homepage = "https://github.com/gkedge/runtime-syspath"
repository = "https://github.com/gkedge/runtime-syspath"
license = "MIT"
keywords = ["testing", "sys.path", "packaging", "dependency", "infer", "pyproject.toml"]
include = ["docs/**/*"]

classifiers = [
        "Programming Language :: Python :: 3",
        "Topic :: Software Development :: Testing",
        "Topic :: Software Development :: Libraries",
	    "Topic :: Utilities",
        "Operating System :: OS Independent",
        "Natural Language :: English",
        "Intended Audience :: Developers",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/gkedge/runtime-syspath/issues"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
wheel = "tox-wheel"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
