[tool.poetry]
name = "src-into-sys-path"
version = "0.1.0"
description = "Provide utility function to find each 'src' directory under working directory and add it to sys.path."
authors = ["Greg Kedge <gregwork@kedges.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
wheel = "tox-wheel"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
